[package]
name = "runtime-interop"
authors = ["Noah Kennedy <nkennedy@cloudflare.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["io-util"] }
futures = "0.3.21"